name: KhoKhoangSanPlus
version: '${project.version}'
main: com.hongminh54.storage.Storage
author: VoChiDanh, hongminh54, TYBZI
description: "${project.description}"
api-version: '1.13'
softdepend:
  - WorldGuard
  - PlaceholderAPI
commands:
  storage:
    description: Main command
    aliases:
      - kho
      - kks
permissions:
  storage.toggle:
    description: quyền bật tắt tự động nhặt vật phẩm
    default: true
  storage.stats:
    description: Xem thống kê hoạt động khai thác
    default: true
  storage.transfer:
    description: Quyền chuyển tài nguyên cho người chơi khác
    default: true
  storage.transfer.others:
    description: Cho phép xem lịch sử chuyển kho của người chơi khác
    default: true
  storage.leaderboard:
    description: Xem bảng xếp hạng người chơi
    default: true
  storage.event:
    description: Quản lý sự kiện khai thác
    default: op
  storage.admin:
    description: quyền admin
    default: op
  storage.admin.add:
    description: quyền thêm vật phẩm cho người chơi
    default: op
  storage.admin.remove:
    description: quyền xóa vật phẩm của người chơi
    default: op
  storage.admin.set:
    description: quyền set vật phẩm cho người chơi
    default: op
  storage.admin.max:
    description: quyền set số lượng tối đa người chơi có thể lưu trữ
    default: op
  storage.admin.reload:
    description: quyền tải lại config
    default: op
  storage.admin.update:
    description: quyền tải xuống bản cập nhật mới nhất từ GitHub
    default: op
  storage.admin.resetleaderboard:
    description: Quyền reset bảng xếp hạng
    default: op
  storage.admin.resetstats:
    description: Quyền reset thống kê của người chơi
    default: op
  storage.log.all:
    description: Cho phép xem toàn bộ lịch sử chuyển kho không bị giới hạn
    default: true
